# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenColorIO Project.
#
# GitHub Actions workflow file
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on:
  push:

jobs:
  # ---------------------------------------------------------------------------
  # Windows
  # ---------------------------------------------------------------------------
  # TODO: Install pythonXX_d.lib (or work around it being needed) to support 
  #       Debug build testing with Python bindings and docs enabled.

  windows:
    name: 'Windows 2019 
      <MSVC 16.4 
       config=${{ matrix.build-type }}, 
       shared=${{ matrix.build-shared }}, 
       sse=${{ matrix.use-sse }}, 
       cxx=${{ matrix.cxx-standard }}, 
       python=${{ matrix.python-version }}, 
       docs=${{ matrix.build-docs }}>'
    runs-on: windows-2019
    strategy:
      matrix:
        build: [2]
        include:
          # Static, no SSE
          - build: 2
            build-type: Release
            build-shared: 'OFF'
            build-docs: 'OFF'
            build-gpu: 'OFF'
            use-headless: 'OFF'
            use-sse: 'OFF'
            cxx-standard: 11
            python-version: 3.7
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install docs env
        run: share/ci/scripts/windows/install_docs_env.sh
        shell: bash
        if: matrix.build-docs == 'ON'
      - name: Install tests env
        run: share/ci/scripts/windows/install_tests_env.sh
      - name: Create build directories
        run: |
          mkdir _install
          mkdir _build
        shell: bash
      - name: Configure
        run: |
          cmake ../. \
                -DCMAKE_INSTALL_PREFIX=../_install \
                -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} \
                -DCMAKE_GENERATOR_PLATFORM=x64 \
                -DBUILD_SHARED_LIBS=${{ matrix.build-shared }} \
                -DOCIO_BUILD_DOCS=${{ matrix.build-docs }} \
                -DOCIO_BUILD_GPU_TESTS=${{ matrix.build-gpu }} \
                -DOCIO_USE_HEADLESS=${{ matrix.use-headless }} \
                -DOCIO_USE_SSE=${{ matrix.use-sse }} \
                -DOCIO_INSTALL_EXT_PACKAGES=ALL \
                -DOCIO_WARNING_AS_ERROR=ON \
                -DPython_EXECUTABLE=$(which python)
        shell: bash
        working-directory: _build
      - name: Build
        run: |
          cmake --build . \
                --target install \
                --config ${{ matrix.build-type }}
        shell: bash
        working-directory: _build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.exe
